// frontend/packages/react/src/layout/AppLayout.tsx
import React, { useEffect, useMemo, useState } from "react";
import { Outlet, useLocation, useMatches, useNavigate } from "react-router-dom";
import { AppConstConfig } from "@app/shared";
import { useTheme } from "../hooks/useTheme";
import type { AppMenuItem } from "../router/types";
import { SidebarMenuItem } from "./SidebarMenuItem";

function activeEditable(): HTMLInputElement | HTMLTextAreaElement | HTMLElement | null {
  const el = document.activeElement as HTMLElement | null;
  if (!el) return null;
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) return el;
  if (el.isContentEditable) return el;
  return null;
}

function performCopy(): boolean {
  const selection = window.getSelection();
  const text = selection?.toString();
  if (text) {
    navigator.clipboard?.writeText(text).catch(() => {});
    return true;
  }
  const el = activeEditable();
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
    const value = el.value;
    const start = el.selectionStart ?? 0;
    const end = el.selectionEnd ?? value.length;
    const chunk = value.slice(start, end) || value;
    navigator.clipboard?.writeText(chunk).catch(() => {});
    return true;
  }
  return false;
}

function performCut(): boolean {
  const el = activeEditable();
  if (!el) return false;
  if (performCopy()) {
    if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
      const start = el.selectionStart ?? 0;
      const end = el.selectionEnd ?? el.value.length;
      const next = el.value.slice(0, start) + el.value.slice(end);
      el.value = next;
      el.setSelectionRange(start, start);
      el.dispatchEvent(new Event("input", { bubbles: true }));
      return true;
    }
    if (el.isContentEditable) {
      document.execCommand("cut");
      return true;
    }
  }
  return false;
}

function performPaste(): boolean {
  const el = activeEditable();
  if (!el || !navigator.clipboard?.readText) return false;
  navigator.clipboard
    .readText()
    .then((text) => {
      if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
        const start = el.selectionStart ?? 0;
        const end = el.selectionEnd ?? start;
        el.setRangeText(text, start, end, "end");
        el.dispatchEvent(new Event("input", { bubbles: true }));
      } else if (el.isContentEditable) {
        document.execCommand("insertText", false, text);
      }
    })
    .catch(() => {});
  return true;
}

function performSelectAll(): boolean {
  const el = activeEditable();
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
    el.select();
    return true;
  }
  if (el?.isContentEditable) {
    document.execCommand("selectAll");
    return true;
  }
  const selection = window.getSelection();
  if (selection) {
    const range = document.createRange();
    range.selectNodeContents(document.body);
    selection.removeAllRanges();
    selection.addRange(range);
    return true;
  }
  return false;
}

function performUndo(action: "undo" | "redo"): boolean {
  document.execCommand(action);
  return true;
}

function handleClipboardHotkeys(e: KeyboardEvent): boolean {
  const meta = e.metaKey || e.ctrlKey;
  if (!meta) return false;
  const key = e.key.toLowerCase();
  if (key === "c") return performCopy();
  if (key === "v") return performPaste();
  if (key === "x") return performCut();
  if (key === "a") return performSelectAll();
  if (key === "z") return performUndo(e.shiftKey ? "redo" : "undo");
  if (key === "y") return performUndo("redo");
  return false;
}

export const AppLayout: React.FC<{ menus: AppMenuItem[] }> = ({ menus }) => {
  const location = useLocation();
  const matches = useMatches();
  const navigate = useNavigate();
  const { theme, themeClass, isCrt, maskStyle, backdropStyle, setTheme } = useTheme();
  const isProd = import.meta.env.PROD;
  const clientHost = typeof window !== "undefined" ? window.location.hostname : "localhost";
  const devPort = typeof window !== "undefined" ? window.location.port : "";
  const [collapsed, setCollapsed] = useState(false);
  const [tabs, setTabs] = useState<{ title: string; path: string }[]>([]);
  const [displayPort, setDisplayPort] = useState("");
  const [tabMenuOpen, setTabMenuOpen] = useState(false);
  const [copyTip, setCopyTip] = useState("点击复制");

  const displayAddress = useMemo(() => {
    const port = isProd ? displayPort : devPort || displayPort;
    const host = clientHost || "localhost";
    return port ? `${host}:${port}` : host;
  }, [clientHost, devPort, displayPort, isProd]);

  const copyAddress = async () => {
    try {
      await navigator.clipboard.writeText(displayAddress);
      setCopyTip("已复制!");
      setTimeout(() => setCopyTip("点击复制"), 1500);
    } catch {
      setCopyTip("复制失败");
      setTimeout(() => setCopyTip("点击复制"), 1500);
    }
  };

  const currentTitle = useMemo(() => {
    const last = matches[matches.length - 1];
    return (last?.handle as any)?.title ?? last?.pathname ?? location.pathname;
  }, [matches, location.pathname]);

  const addTab = () => {
    setTabs((prev) => {
      if (prev.some((t) => t.path === location.pathname)) return prev;
      return [...prev, { title: currentTitle, path: location.pathname }];
    });
  };

  useEffect(() => {
    addTab();
  }, [location.pathname, currentTitle]);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (handleClipboardHotkeys(e)) {
        e.preventDefault();
        e.stopPropagation();
      }
    };
    window.addEventListener("keydown", handler, true);
    return () => window.removeEventListener("keydown", handler, true);
  }, []);

  const closeTab = (path: string) => {
    setTabs((prev) => {
      const next = prev.filter((t) => t.path !== path);
      if (path === location.pathname) {
        const fallback = next[next.length - 1];
        navigate(fallback?.path || "/");
      }
      return next;
    });
  };

  const closeOthers = () => setTabs((prev) => prev.filter((t) => t.path === location.pathname));
  const closeLeft = () =>
    setTabs((prev) => {
      const idx = prev.findIndex((t) => t.path === location.pathname);
      if (idx <= 0) return prev;
      return prev.slice(idx);
    });
  const closeRight = () =>
    setTabs((prev) => {
      const idx = prev.findIndex((t) => t.path === location.pathname);
      if (idx === -1) return prev;
      return prev.slice(0, idx + 1);
    });
  const closeAll = () => {
    setTabs([]);
    navigate("/");
  };

  const handleNav = (fullPath: string) => navigate(fullPath);

  useEffect(() => {
    if (!isProd) return;
    (async () => {
      try {
        const res = await fetch("/api/meta", { method: "POST" });
        const data = await res.json();
        if (data?.code == 0) setDisplayPort(String(data.data?.port ?? ""));
      } catch {
        // ignore
      }
    })();
  }, [isProd]);

  return (
    <div className={`app-shell ${themeClass} ${collapsed ? "sidebar-collapsed" : ""}`}>
      {isCrt && <div className="crt-layer backdrop" style={backdropStyle} />}
      {isCrt && <div className="crt-layer mask" style={maskStyle} />}
      {isCrt && <div className="crt-layer scanlines" />}
      {isCrt && <div className="crt-layer vignette" />}
      <aside className={`shell-sidebar ${collapsed ? "collapsed" : ""}`}>
        <div className="brand">
          <div className="brand-name">{AppConstConfig.displayName}</div>
          <small className="brand-sub">模块化工具箱框架</small>
        </div>
        <button className="menu-toggle" onClick={() => setCollapsed((v) => !v)}>
          {collapsed ? "展开" : "收起"}
        </button>
        <nav className="menu">
          {menus.map((menu) => (
            <SidebarMenuItem key={menu.fullPath} menu={menu} activePath={location.pathname} collapsed={collapsed} depth={0} onNavigate={handleNav} />
          ))}
        </nav>
        <div className="sidebar-footer">
          <div className="sidebar-section">
            <div className="sidebar-label">主题</div>
            <div className="theme-row compact">
              <button className={theme === "e-ink" ? "active" : ""} onClick={() => setTheme("e-ink")}>
                墨水屏
              </button>
              <button className={theme === "crt-amber" ? "active" : ""} onClick={() => setTheme("crt-amber")}>
                琥珀CRT
              </button>
              <button className={theme === "crt-green" ? "active" : ""} onClick={() => setTheme("crt-green")}>
                绿色CRT
              </button>
            </div>
          </div>
          <div className="sidebar-section">
            <div className="sidebar-label">浏览器IP:PORT</div>
            <div className="sidebar-link-box copyable" onClick={copyAddress} title={copyTip}>
              <span>{displayAddress}</span>
              <svg className="copy-icon" viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
              </svg>
            </div>
          </div>
        </div>
      </aside>
      <div className="shell-main">
        <header className="shell-header">
          <div className="header-title">
            <span>工具栏</span>
          </div>
          <div className="header-actions"></div>
        </header>
        <div className="tab-bar">
          {tabs.map((tab) => (
            <div key={tab.path} className={`tab ${tab.path === location.pathname ? "active" : ""}`} onClick={() => navigate(tab.path)}>
              <span className="tab-title">{tab.title}</span>
              <button className="tab-close" onClick={(e) => { e.stopPropagation(); closeTab(tab.path); }}>
                ×
              </button>
            </div>
          ))}
          <div className="tab-actions">
            {tabMenuOpen && (
              <div className="tab-inline-menu">
                <button onClick={() => { closeLeft(); setTabMenuOpen(false); }}>关闭左侧</button>
                <button onClick={() => { closeRight(); setTabMenuOpen(false); }}>关闭右侧</button>
                <button onClick={() => { closeOthers(); setTabMenuOpen(false); }}>关闭其他</button>
                <button onClick={() => { closeAll(); setTabMenuOpen(false); }}>全部关闭</button>
              </div>
            )}
            <button className="tab-dropdown-trigger" onClick={() => setTabMenuOpen((v) => !v)}>
              关闭
            </button>
          </div>
        </div>
        <main className="shell-content">
          <Outlet />
        </main>
      </div>
    </div>
  );
};

// frontend/packages/vue/src/layout/AppLayout.vue
<template>
  <div class="app-shell" :class="[themeClass, { 'sidebar-collapsed': collapsed }]">
    <div v-if="isCrt" class="crt-layer backdrop" :style="backdropStyle"></div>
    <div v-if="isCrt" class="crt-layer mask" :style="maskStyle"></div>
    <div v-if="isCrt" class="crt-layer scanlines"></div>
    <div v-if="isCrt" class="crt-layer vignette"></div>
    <aside class="shell-sidebar" :class="{ collapsed }">
      <div class="brand">
        <div class="brand-name">{{ AppConstConfig.displayName }}</div>
        <small class="brand-sub">模块化工具箱框架</small>
      </div>
      <button class="menu-toggle" @click="collapsed = !collapsed">{{ collapsed ? "展开" : "收起" }}</button>
        <nav class="menu">
          <SidebarMenuItem
            v-for="menu in menus"
            :key="menu.fullPath"
            :menu="menu"
            :active-path="route.path"
            :collapsed="collapsed"
            :depth="0"
            @navigate="navigate"
          />
        </nav>
      <div class="sidebar-footer">
        <div class="sidebar-section">
          <div class="sidebar-label">主题</div>
          <div class="theme-row compact">
            <button :class="{ active: theme === 'e-ink' }" @click="setTheme('e-ink')">墨水屏</button>
            <button :class="{ active: theme === 'crt-amber' }" @click="setTheme('crt-amber')">琥珀CRT</button>
            <button :class="{ active: theme === 'crt-green' }" @click="setTheme('crt-green')">绿色CRT</button>
          </div>
        </div>
        <div class="sidebar-section">
          <div class="sidebar-label">浏览器IP:PORT</div>
          <div class="sidebar-link-box copyable" @click="copyAddress" :title="copyTip">
            <span>{{ displayAddress }}</span>
            <svg class="copy-icon" viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
              <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
            </svg>
          </div>
        </div>
      </div>
    </aside>
    <div class="shell-main">
      <header class="shell-header">
        <div class="header-title">
          <span>工具栏</span>
        </div>
        <div class="header-actions">
          <slot name="header-right" />
        </div>
      </header>
      <div class="tab-bar">
        <div
          v-for="tab in tabs"
          :key="tab.path"
          class="tab"
          :class="{ active: tab.path === route.path }"
          @click="navigate(tab.path)"
        >
          <span class="tab-title">{{ tab.title }}</span>
          <button class="tab-close" @click.stop="closeTab(tab.path)">×</button>
        </div>
        <div class="tab-actions">
          <div v-if="tabMenuOpen" class="tab-inline-menu">
            <button @click="() => { closeLeft(); tabMenuOpen = false; }">关闭左侧</button>
            <button @click="() => { closeRight(); tabMenuOpen = false; }">关闭右侧</button>
            <button @click="() => { closeOthers(); tabMenuOpen = false; }">关闭其他</button>
            <button @click="() => { closeAll(); tabMenuOpen = false; }">全部关闭</button>
          </div>
          <button class="tab-dropdown-trigger" @click="tabMenuOpen = !tabMenuOpen">关闭</button>
        </div>
      </div>
      <main class="shell-content">
        <RouterView />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onBeforeUnmount, ref, watch } from "vue";
import { useRoute, useRouter, RouterView } from "vue-router";
import { AppConstConfig } from "@app/shared";
import type { AppMenuItem } from "../router/types";
import { useTheme } from "../hooks/useTheme";
import SidebarMenuItem from "./SidebarMenuItem.vue";

const props = defineProps<{
  menus: AppMenuItem[];
}>();

const router = useRouter();
const route = useRoute();
const { theme, themeClass, isCrt, maskStyle, backdropStyle, setTheme } = useTheme();

const collapsed = ref(false);
const tabs = ref<{ title: string; path: string }[]>([]);
const tabMenuOpen = ref(false);
const displayPort = ref<string>("");
const copyTip = ref("点击复制");
const isProd = import.meta.env.PROD;
const clientHost = typeof window !== "undefined" ? window.location.hostname : "localhost";
const devPort = typeof window !== "undefined" ? window.location.port : "";

const displayAddress = computed(() => {
  const port = isProd ? displayPort.value : devPort || displayPort.value;
  const host = clientHost || "localhost";
  return port ? `${host}:${port}` : host;
});

const copyAddress = async () => {
  try {
    await navigator.clipboard.writeText(displayAddress.value);
    copyTip.value = "已复制!";
    setTimeout(() => {
      copyTip.value = "点击复制";
    }, 1500);
  } catch {
    copyTip.value = "复制失败";
    setTimeout(() => {
      copyTip.value = "点击复制";
    }, 1500);
  }
};

const addTab = () => {
  const title = (route.meta?.title as string) || route.name?.toString() || route.path;
  if (!tabs.value.find((t) => t.path === route.path)) {
    tabs.value.push({ title, path: route.path });
  }
};

const closeTab = (path: string) => {
  const idx = tabs.value.findIndex((t) => t.path === path);
  if (idx === -1) return;
  tabs.value.splice(idx, 1);
  if (path === route.path) {
    const fallback = tabs.value[idx - 1] || tabs.value[idx] || tabs.value[tabs.value.length - 1];
    router.push(fallback?.path || "/");
  }
};

const closeOthers = () => {
  tabs.value = tabs.value.filter((t) => t.path === route.path);
};
const closeLeft = () => {
  const idx = tabs.value.findIndex((t) => t.path === route.path);
  if (idx > 0) tabs.value = tabs.value.slice(idx);
};
const closeRight = () => {
  const idx = tabs.value.findIndex((t) => t.path === route.path);
  if (idx !== -1) tabs.value = tabs.value.slice(0, idx + 1);
};
const closeAll = () => {
  tabs.value = [];
  router.push("/");
};

const navigate = (fullPath: string) => router.push(fullPath);

const fetchPort = async () => {
  try {
    const res = await fetch("/api/meta", { method: "POST" });
    const data = await res.json();
    if (data?.code == 0) {
      displayPort.value = String(data.data?.port ?? "");
    }
  } catch {
    // ignore
  }
};

watch(
  () => route.path,
  () => {
    addTab();
  },
  { immediate: true }
);

const handleKeydown = (e: KeyboardEvent) => {
  if (handleClipboardHotkeys(e)) {
    e.preventDefault();
    e.stopPropagation();
  }
};

onMounted(() => {
  if (isProd) {
    fetchPort();
  }
  window.addEventListener("keydown", handleKeydown, true);
});
onBeforeUnmount(() => {
  window.removeEventListener("keydown", handleKeydown, true);
});

function handleClipboardHotkeys(e: KeyboardEvent): boolean {
  const meta = e.metaKey || e.ctrlKey;
  if (!meta) return false;
  const key = e.key.toLowerCase();
  if (key === "c") return performCopy();
  if (key === "v") return performPaste();
  if (key === "x") return performCut();
  if (key === "a") return performSelectAll();
  if (key === "z") return performUndo(e.shiftKey ? "redo" : "undo");
  if (key === "y") return performUndo("redo");
  return false;
}

function activeEditable(): HTMLInputElement | HTMLTextAreaElement | HTMLElement | null {
  const el = document.activeElement as HTMLElement | null;
  if (!el) return null;
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) return el;
  if (el.isContentEditable) return el;
  return null;
}

function performCopy(): boolean {
  const selection = window.getSelection();
  const text = selection?.toString();
  if (text) {
    navigator.clipboard?.writeText(text).catch(() => {});
    return true;
  }
  const el = activeEditable();
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
    const value = el.value;
    const start = el.selectionStart ?? 0;
    const end = el.selectionEnd ?? value.length;
    const chunk = value.slice(start, end) || value;
    navigator.clipboard?.writeText(chunk).catch(() => {});
    return true;
  }
  return false;
}

function performCut(): boolean {
  const el = activeEditable();
  if (!el) return false;
  if (performCopy()) {
    if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
      const start = el.selectionStart ?? 0;
      const end = el.selectionEnd ?? el.value.length;
      const next = el.value.slice(0, start) + el.value.slice(end);
      el.value = next;
      el.setSelectionRange(start, start);
      el.dispatchEvent(new Event("input", { bubbles: true }));
      return true;
    }
    if (el.isContentEditable) {
      document.execCommand("cut");
      return true;
    }
  }
  return false;
}

function performPaste(): boolean {
  const el = activeEditable();
  if (!el) return false;
  if (!navigator.clipboard?.readText) return false;
  navigator.clipboard
    .readText()
    .then((text) => {
      if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
        const start = el.selectionStart ?? 0;
        const end = el.selectionEnd ?? start;
        el.setRangeText(text, start, end, "end");
        el.dispatchEvent(new Event("input", { bubbles: true }));
      } else if (el.isContentEditable) {
        document.execCommand("insertText", false, text);
      }
    })
    .catch(() => {});
  return true;
}

function performSelectAll(): boolean {
  const el = activeEditable();
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
    el.select();
    return true;
  }
  if (el?.isContentEditable) {
    document.execCommand("selectAll");
    return true;
  }
  const selection = window.getSelection();
  if (selection) {
    const range = document.createRange();
    range.selectNodeContents(document.body);
    selection.removeAllRanges();
    selection.addRange(range);
    return true;
  }
  return false;
}

function performUndo(action: "undo" | "redo"): boolean {
  document.execCommand(action);
  return true;
}
</script>
